"""Added created date field to script model 2

Revision ID: da4a08d36859
Revises: 4e99af2a12a7
Create Date: 2020-05-18 21:42:54.271163

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da4a08d36859'
down_revision = '4e99af2a12a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scripts', sa.Column('created', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scripts', 'created')
    # ### end Alembic commands ###
